-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 15:22:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema csv_prdts2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csv_prdts2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csv_prdts2` DEFAULT CHARACTER SET utf8 ;
USE `csv_prdts2` ;

-- -----------------------------------------------------
-- Table `csv_prdts2`.`famille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csv_prdts2`.`famille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csv_prdts2`.`conditionnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csv_prdts2`.`conditionnement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csv_prdts2`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csv_prdts2`.`produits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(100) NOT NULL,
  `prix` DECIMAL(6,2) NOT NULL,
  `code_art` VARCHAR(45) NOT NULL,
  `famille_id` INT NOT NULL,
  `conditionnement_id` INT NOT NULL,
  PRIMARY KEY (`id`, `famille_id`, `conditionnement_id`),
  INDEX `fk_produits_famille_idx` (`famille_id` ASC) VISIBLE,
  INDEX `fk_produits_conditionnement1_idx` (`conditionnement_id` ASC) VISIBLE,
  CONSTRAINT `fk_produits_famille`
    FOREIGN KEY (`famille_id`)
    REFERENCES `csv_prdts2`.`famille` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_conditionnement1`
    FOREIGN KEY (`conditionnement_id`)
    REFERENCES `csv_prdts2`.`conditionnement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
